### ISSUE TITLE
Fix error when unmounting triggered by window resize (React 17)

### ISSUE THREAD

**Issue by dennisdijkstra** [nihlton/react-peek-element#14]
I’m currently experiencing a similar issue as described here (https://github.com/nihlton/react-peek-element/pull/2) when using this library in combination with React 17. It’s caused by a small change of the timing of the useEffect cleanup function introduced by React 17. 

> In React 17, the effect cleanup function always runs asynchronously — for example, if the component is unmounting, the cleanup runs after the screen has been updated.
> 
> This mirrors how the effects themselves run more closely. In the rare cases where you might want to rely on the synchronous execution, you can switch to useLayoutEffect instead.

Source: https://reactjs.org/blog/2020/08/10/react-v17-rc.html

Example of the bug in effect can be found here: https://codesandbox.io/s/objective-snow-2op2j?file=/src/index.js

I believe replacing useEffect on `line 72` of src/index.js by useLayoutEffect seems to fix the problem. Would you be able to push a fix for this? Thanks!

**Comment by nihlton** [comment]
fixed with https://github.com/nihlton/react-peek-element/commit/3f4860b3b1c9275f43a53c516b145487e41c897a
